/**
 * This file is autogenerated by Scaffold-ETH.
 * You should not edit it manually or your changes might be overwritten.
 */
import { GenericContractsDeclaration } from "~~/utils/scaffold-eth/contract";

const deployedContracts = {
  31337: {
    ObecRegistry: {
      address: "0x5fbdb2315678afecb367f032d93f642f64180aa3",
      abi: [
        {
          type: "constructor",
          inputs: [
            {
              name: "protocolRootNamehash",
              type: "bytes32",
              internalType: "bytes32",
            },
          ],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "PROTOCOL_ROOT_NAMEHASH",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "bytes32",
              internalType: "bytes32",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "addressToNode",
          inputs: [
            {
              name: "",
              type: "address",
              internalType: "address",
            },
          ],
          outputs: [
            {
              name: "",
              type: "bytes32",
              internalType: "bytes32",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "commitmentPool",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "address",
              internalType: "address",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "createNeighborhood",
          inputs: [
            {
              name: "city",
              type: "string",
              internalType: "string",
            },
            {
              name: "name",
              type: "string",
              internalType: "string",
            },
          ],
          outputs: [
            {
              name: "neighborhoodId",
              type: "bytes32",
              internalType: "bytes32",
            },
          ],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "deactivateResource",
          inputs: [
            {
              name: "node",
              type: "bytes32",
              internalType: "bytes32",
            },
          ],
          outputs: [],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "getContenthash",
          inputs: [
            {
              name: "node",
              type: "bytes32",
              internalType: "bytes32",
            },
          ],
          outputs: [
            {
              name: "",
              type: "bytes",
              internalType: "bytes",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "getNeighborhoodMembers",
          inputs: [
            {
              name: "neighborhoodId",
              type: "bytes32",
              internalType: "bytes32",
            },
          ],
          outputs: [
            {
              name: "",
              type: "bytes32[]",
              internalType: "bytes32[]",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "getNeighborhoodResources",
          inputs: [
            {
              name: "neighborhoodId",
              type: "bytes32",
              internalType: "bytes32",
            },
          ],
          outputs: [
            {
              name: "",
              type: "bytes32[]",
              internalType: "bytes32[]",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "getNodeByAddress",
          inputs: [
            {
              name: "wallet",
              type: "address",
              internalType: "address",
            },
          ],
          outputs: [
            {
              name: "",
              type: "bytes32",
              internalType: "bytes32",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "getNodeLabels",
          inputs: [
            {
              name: "node",
              type: "bytes32",
              internalType: "bytes32",
            },
          ],
          outputs: [
            {
              name: "",
              type: "string[]",
              internalType: "string[]",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "getText",
          inputs: [
            {
              name: "node",
              type: "bytes32",
              internalType: "bytes32",
            },
            {
              name: "key",
              type: "string",
              internalType: "string",
            },
          ],
          outputs: [
            {
              name: "",
              type: "string",
              internalType: "string",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "isMember",
          inputs: [
            {
              name: "neighborhoodId",
              type: "bytes32",
              internalType: "bytes32",
            },
            {
              name: "wallet",
              type: "address",
              internalType: "address",
            },
          ],
          outputs: [
            {
              name: "",
              type: "bool",
              internalType: "bool",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "joinNeighborhood",
          inputs: [
            {
              name: "neighborhoodId",
              type: "bytes32",
              internalType: "bytes32",
            },
            {
              name: "label",
              type: "string",
              internalType: "string",
            },
          ],
          outputs: [
            {
              name: "memberNode",
              type: "bytes32",
              internalType: "bytes32",
            },
          ],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "members",
          inputs: [
            {
              name: "",
              type: "bytes32",
              internalType: "bytes32",
            },
          ],
          outputs: [
            {
              name: "wallet",
              type: "address",
              internalType: "address",
            },
            {
              name: "neighborhoodId",
              type: "bytes32",
              internalType: "bytes32",
            },
            {
              name: "label",
              type: "string",
              internalType: "string",
            },
            {
              name: "joinedAt",
              type: "uint64",
              internalType: "uint64",
            },
            {
              name: "active",
              type: "bool",
              internalType: "bool",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "neighborhoodAdmin",
          inputs: [
            {
              name: "neighborhoodId",
              type: "bytes32",
              internalType: "bytes32",
            },
          ],
          outputs: [
            {
              name: "",
              type: "address",
              internalType: "address",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "neighborhoodMembers",
          inputs: [
            {
              name: "",
              type: "bytes32",
              internalType: "bytes32",
            },
            {
              name: "",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          outputs: [
            {
              name: "",
              type: "bytes32",
              internalType: "bytes32",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "neighborhoodResources",
          inputs: [
            {
              name: "",
              type: "bytes32",
              internalType: "bytes32",
            },
            {
              name: "",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          outputs: [
            {
              name: "",
              type: "bytes32",
              internalType: "bytes32",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "neighborhoods",
          inputs: [
            {
              name: "",
              type: "bytes32",
              internalType: "bytes32",
            },
          ],
          outputs: [
            {
              name: "city",
              type: "string",
              internalType: "string",
            },
            {
              name: "name",
              type: "string",
              internalType: "string",
            },
            {
              name: "admin",
              type: "address",
              internalType: "address",
            },
            {
              name: "active",
              type: "bool",
              internalType: "bool",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "owner",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "address",
              internalType: "address",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "registerResource",
          inputs: [
            {
              name: "neighborhoodId",
              type: "bytes32",
              internalType: "bytes32",
            },
            {
              name: "label",
              type: "string",
              internalType: "string",
            },
            {
              name: "resourceType",
              type: "string",
              internalType: "string",
            },
            {
              name: "fundedBy",
              type: "address",
              internalType: "address",
            },
          ],
          outputs: [
            {
              name: "resourceNode",
              type: "bytes32",
              internalType: "bytes32",
            },
          ],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "resources",
          inputs: [
            {
              name: "",
              type: "bytes32",
              internalType: "bytes32",
            },
          ],
          outputs: [
            {
              name: "neighborhoodId",
              type: "bytes32",
              internalType: "bytes32",
            },
            {
              name: "label",
              type: "string",
              internalType: "string",
            },
            {
              name: "resourceType",
              type: "string",
              internalType: "string",
            },
            {
              name: "fundedBy",
              type: "address",
              internalType: "address",
            },
            {
              name: "active",
              type: "bool",
              internalType: "bool",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "setCommitmentPool",
          inputs: [
            {
              name: "pool",
              type: "address",
              internalType: "address",
            },
          ],
          outputs: [],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "setContenthash",
          inputs: [
            {
              name: "node",
              type: "bytes32",
              internalType: "bytes32",
            },
            {
              name: "hash",
              type: "bytes",
              internalType: "bytes",
            },
          ],
          outputs: [],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "setText",
          inputs: [
            {
              name: "node",
              type: "bytes32",
              internalType: "bytes32",
            },
            {
              name: "key",
              type: "string",
              internalType: "string",
            },
            {
              name: "value",
              type: "string",
              internalType: "string",
            },
          ],
          outputs: [],
          stateMutability: "nonpayable",
        },
        {
          type: "event",
          name: "CommitmentPoolSet",
          inputs: [
            {
              name: "pool",
              type: "address",
              indexed: false,
              internalType: "address",
            },
          ],
          anonymous: false,
        },
        {
          type: "event",
          name: "ContenthashSet",
          inputs: [
            {
              name: "node",
              type: "bytes32",
              indexed: true,
              internalType: "bytes32",
            },
            {
              name: "hash",
              type: "bytes",
              indexed: false,
              internalType: "bytes",
            },
          ],
          anonymous: false,
        },
        {
          type: "event",
          name: "MemberJoined",
          inputs: [
            {
              name: "neighborhoodId",
              type: "bytes32",
              indexed: true,
              internalType: "bytes32",
            },
            {
              name: "memberNode",
              type: "bytes32",
              indexed: true,
              internalType: "bytes32",
            },
            {
              name: "wallet",
              type: "address",
              indexed: false,
              internalType: "address",
            },
            {
              name: "label",
              type: "string",
              indexed: false,
              internalType: "string",
            },
          ],
          anonymous: false,
        },
        {
          type: "event",
          name: "NeighborhoodCreated",
          inputs: [
            {
              name: "neighborhoodId",
              type: "bytes32",
              indexed: true,
              internalType: "bytes32",
            },
            {
              name: "city",
              type: "string",
              indexed: false,
              internalType: "string",
            },
            {
              name: "name",
              type: "string",
              indexed: false,
              internalType: "string",
            },
            {
              name: "admin",
              type: "address",
              indexed: false,
              internalType: "address",
            },
          ],
          anonymous: false,
        },
        {
          type: "event",
          name: "ResourceDeactivated",
          inputs: [
            {
              name: "neighborhoodId",
              type: "bytes32",
              indexed: true,
              internalType: "bytes32",
            },
            {
              name: "resourceNode",
              type: "bytes32",
              indexed: true,
              internalType: "bytes32",
            },
          ],
          anonymous: false,
        },
        {
          type: "event",
          name: "ResourceRegistered",
          inputs: [
            {
              name: "neighborhoodId",
              type: "bytes32",
              indexed: true,
              internalType: "bytes32",
            },
            {
              name: "resourceNode",
              type: "bytes32",
              indexed: true,
              internalType: "bytes32",
            },
            {
              name: "label",
              type: "string",
              indexed: false,
              internalType: "string",
            },
            {
              name: "resourceType",
              type: "string",
              indexed: false,
              internalType: "string",
            },
          ],
          anonymous: false,
        },
        {
          type: "event",
          name: "TextSet",
          inputs: [
            {
              name: "node",
              type: "bytes32",
              indexed: true,
              internalType: "bytes32",
            },
            {
              name: "key",
              type: "string",
              indexed: false,
              internalType: "string",
            },
            {
              name: "value",
              type: "string",
              indexed: false,
              internalType: "string",
            },
          ],
          anonymous: false,
        },
        {
          type: "error",
          name: "AlreadyExists",
          inputs: [],
        },
        {
          type: "error",
          name: "NeighborhoodNotFound",
          inputs: [],
        },
        {
          type: "error",
          name: "NotOwner",
          inputs: [],
        },
        {
          type: "error",
          name: "NotPool",
          inputs: [],
        },
        {
          type: "error",
          name: "PoolAlreadySet",
          inputs: [],
        },
        {
          type: "error",
          name: "ResourceNotActive",
          inputs: [],
        },
        {
          type: "error",
          name: "Unauthorized",
          inputs: [],
        },
      ],
      inheritedFunctions: {},
      deployedOnBlock: 1,
    },
    MockUSDC: {
      address: "0xe7f1725e7734ce288f8367e1bb143e90bb3f0512",
      abi: [
        {
          type: "constructor",
          inputs: [],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "allowance",
          inputs: [
            {
              name: "owner",
              type: "address",
              internalType: "address",
            },
            {
              name: "spender",
              type: "address",
              internalType: "address",
            },
          ],
          outputs: [
            {
              name: "",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "approve",
          inputs: [
            {
              name: "spender",
              type: "address",
              internalType: "address",
            },
            {
              name: "value",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          outputs: [
            {
              name: "",
              type: "bool",
              internalType: "bool",
            },
          ],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "balanceOf",
          inputs: [
            {
              name: "account",
              type: "address",
              internalType: "address",
            },
          ],
          outputs: [
            {
              name: "",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "decimals",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "uint8",
              internalType: "uint8",
            },
          ],
          stateMutability: "pure",
        },
        {
          type: "function",
          name: "mint",
          inputs: [
            {
              name: "to",
              type: "address",
              internalType: "address",
            },
            {
              name: "amount",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          outputs: [],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "name",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "string",
              internalType: "string",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "symbol",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "string",
              internalType: "string",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "totalSupply",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "transfer",
          inputs: [
            {
              name: "to",
              type: "address",
              internalType: "address",
            },
            {
              name: "value",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          outputs: [
            {
              name: "",
              type: "bool",
              internalType: "bool",
            },
          ],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "transferFrom",
          inputs: [
            {
              name: "from",
              type: "address",
              internalType: "address",
            },
            {
              name: "to",
              type: "address",
              internalType: "address",
            },
            {
              name: "value",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          outputs: [
            {
              name: "",
              type: "bool",
              internalType: "bool",
            },
          ],
          stateMutability: "nonpayable",
        },
        {
          type: "event",
          name: "Approval",
          inputs: [
            {
              name: "owner",
              type: "address",
              indexed: true,
              internalType: "address",
            },
            {
              name: "spender",
              type: "address",
              indexed: true,
              internalType: "address",
            },
            {
              name: "value",
              type: "uint256",
              indexed: false,
              internalType: "uint256",
            },
          ],
          anonymous: false,
        },
        {
          type: "event",
          name: "Transfer",
          inputs: [
            {
              name: "from",
              type: "address",
              indexed: true,
              internalType: "address",
            },
            {
              name: "to",
              type: "address",
              indexed: true,
              internalType: "address",
            },
            {
              name: "value",
              type: "uint256",
              indexed: false,
              internalType: "uint256",
            },
          ],
          anonymous: false,
        },
        {
          type: "error",
          name: "ERC20InsufficientAllowance",
          inputs: [
            {
              name: "spender",
              type: "address",
              internalType: "address",
            },
            {
              name: "allowance",
              type: "uint256",
              internalType: "uint256",
            },
            {
              name: "needed",
              type: "uint256",
              internalType: "uint256",
            },
          ],
        },
        {
          type: "error",
          name: "ERC20InsufficientBalance",
          inputs: [
            {
              name: "sender",
              type: "address",
              internalType: "address",
            },
            {
              name: "balance",
              type: "uint256",
              internalType: "uint256",
            },
            {
              name: "needed",
              type: "uint256",
              internalType: "uint256",
            },
          ],
        },
        {
          type: "error",
          name: "ERC20InvalidApprover",
          inputs: [
            {
              name: "approver",
              type: "address",
              internalType: "address",
            },
          ],
        },
        {
          type: "error",
          name: "ERC20InvalidReceiver",
          inputs: [
            {
              name: "receiver",
              type: "address",
              internalType: "address",
            },
          ],
        },
        {
          type: "error",
          name: "ERC20InvalidSender",
          inputs: [
            {
              name: "sender",
              type: "address",
              internalType: "address",
            },
          ],
        },
        {
          type: "error",
          name: "ERC20InvalidSpender",
          inputs: [
            {
              name: "spender",
              type: "address",
              internalType: "address",
            },
          ],
        },
      ],
      inheritedFunctions: {},
      deployedOnBlock: 3,
    },
    CommitmentPool: {
      address: "0x9fe46736679d2d9a65f0992f2272de9f3c7fa6e0",
      abi: [
        {
          type: "constructor",
          inputs: [
            {
              name: "_registry",
              type: "address",
              internalType: "address",
            },
            {
              name: "_usdc",
              type: "address",
              internalType: "address",
            },
          ],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "MILESTONE_0_BPS",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "uint16",
              internalType: "uint16",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "MILESTONE_1_BPS",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "uint16",
              internalType: "uint16",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "MILESTONE_2_BPS",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "uint16",
              internalType: "uint16",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "attest",
          inputs: [
            {
              name: "proposalNode",
              type: "bytes32",
              internalType: "bytes32",
            },
          ],
          outputs: [],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "checkExpiry",
          inputs: [
            {
              name: "proposalNode",
              type: "bytes32",
              internalType: "bytes32",
            },
          ],
          outputs: [],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "claimRefund",
          inputs: [
            {
              name: "proposalNode",
              type: "bytes32",
              internalType: "bytes32",
            },
          ],
          outputs: [],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "claimWarrantyMilestone",
          inputs: [
            {
              name: "proposalNode",
              type: "bytes32",
              internalType: "bytes32",
            },
          ],
          outputs: [],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "commit",
          inputs: [
            {
              name: "proposalNode",
              type: "bytes32",
              internalType: "bytes32",
            },
            {
              name: "amount",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          outputs: [],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "commitments",
          inputs: [
            {
              name: "",
              type: "bytes32",
              internalType: "bytes32",
            },
            {
              name: "",
              type: "address",
              internalType: "address",
            },
          ],
          outputs: [
            {
              name: "",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "createProposal",
          inputs: [
            {
              name: "p",
              type: "tuple",
              internalType: "struct CommitmentPool.CreateParams",
              components: [
                {
                  name: "neighborhoodId",
                  type: "bytes32",
                  internalType: "bytes32",
                },
                {
                  name: "label",
                  type: "string",
                  internalType: "string",
                },
                {
                  name: "executor",
                  type: "address",
                  internalType: "address",
                },
                {
                  name: "targetAmount",
                  type: "uint256",
                  internalType: "uint256",
                },
                {
                  name: "minMembers",
                  type: "uint256",
                  internalType: "uint256",
                },
                {
                  name: "deadline",
                  type: "uint64",
                  internalType: "uint64",
                },
                {
                  name: "warrantyDuration",
                  type: "uint64",
                  internalType: "uint64",
                },
                {
                  name: "attestationThreshold",
                  type: "uint256",
                  internalType: "uint256",
                },
                {
                  name: "resourceType",
                  type: "string",
                  internalType: "string",
                },
                {
                  name: "description",
                  type: "string",
                  internalType: "string",
                },
              ],
            },
          ],
          outputs: [
            {
              name: "proposalNode",
              type: "bytes32",
              internalType: "bytes32",
            },
          ],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "getAttesters",
          inputs: [
            {
              name: "node",
              type: "bytes32",
              internalType: "bytes32",
            },
          ],
          outputs: [
            {
              name: "",
              type: "address[]",
              internalType: "address[]",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "getProposal",
          inputs: [
            {
              name: "node",
              type: "bytes32",
              internalType: "bytes32",
            },
          ],
          outputs: [
            {
              name: "",
              type: "tuple",
              internalType: "struct CommitmentPool.Proposal",
              components: [
                {
                  name: "neighborhoodId",
                  type: "bytes32",
                  internalType: "bytes32",
                },
                {
                  name: "label",
                  type: "string",
                  internalType: "string",
                },
                {
                  name: "executor",
                  type: "address",
                  internalType: "address",
                },
                {
                  name: "targetAmount",
                  type: "uint256",
                  internalType: "uint256",
                },
                {
                  name: "minMembers",
                  type: "uint256",
                  internalType: "uint256",
                },
                {
                  name: "deadline",
                  type: "uint64",
                  internalType: "uint64",
                },
                {
                  name: "warrantyDuration",
                  type: "uint64",
                  internalType: "uint64",
                },
                {
                  name: "attestedAt",
                  type: "uint64",
                  internalType: "uint64",
                },
                {
                  name: "attestationThreshold",
                  type: "uint256",
                  internalType: "uint256",
                },
                {
                  name: "totalCommitted",
                  type: "uint256",
                  internalType: "uint256",
                },
                {
                  name: "memberCount",
                  type: "uint256",
                  internalType: "uint256",
                },
                {
                  name: "attestationCount",
                  type: "uint256",
                  internalType: "uint256",
                },
                {
                  name: "status",
                  type: "uint8",
                  internalType: "enum CommitmentPool.Status",
                },
                {
                  name: "milestoneReleased",
                  type: "bool[3]",
                  internalType: "bool[3]",
                },
              ],
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "hasAttested",
          inputs: [
            {
              name: "",
              type: "bytes32",
              internalType: "bytes32",
            },
            {
              name: "",
              type: "address",
              internalType: "address",
            },
          ],
          outputs: [
            {
              name: "",
              type: "bool",
              internalType: "bool",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "raiseDispute",
          inputs: [
            {
              name: "proposalNode",
              type: "bytes32",
              internalType: "bytes32",
            },
          ],
          outputs: [],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "registry",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "address",
              internalType: "contract IRegistry",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "resolveDispute",
          inputs: [
            {
              name: "proposalNode",
              type: "bytes32",
              internalType: "bytes32",
            },
            {
              name: "refund",
              type: "bool",
              internalType: "bool",
            },
          ],
          outputs: [],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "status",
          inputs: [
            {
              name: "node",
              type: "bytes32",
              internalType: "bytes32",
            },
          ],
          outputs: [
            {
              name: "",
              type: "uint8",
              internalType: "enum CommitmentPool.Status",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "usdc",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "address",
              internalType: "contract IERC20",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "withdraw",
          inputs: [
            {
              name: "proposalNode",
              type: "bytes32",
              internalType: "bytes32",
            },
          ],
          outputs: [],
          stateMutability: "nonpayable",
        },
        {
          type: "event",
          name: "Attested",
          inputs: [
            {
              name: "proposalNode",
              type: "bytes32",
              indexed: true,
              internalType: "bytes32",
            },
            {
              name: "member",
              type: "address",
              indexed: true,
              internalType: "address",
            },
            {
              name: "attestationCount",
              type: "uint256",
              indexed: false,
              internalType: "uint256",
            },
          ],
          anonymous: false,
        },
        {
          type: "event",
          name: "Committed",
          inputs: [
            {
              name: "proposalNode",
              type: "bytes32",
              indexed: true,
              internalType: "bytes32",
            },
            {
              name: "member",
              type: "address",
              indexed: true,
              internalType: "address",
            },
            {
              name: "amount",
              type: "uint256",
              indexed: false,
              internalType: "uint256",
            },
            {
              name: "totalCommitted",
              type: "uint256",
              indexed: false,
              internalType: "uint256",
            },
          ],
          anonymous: false,
        },
        {
          type: "event",
          name: "DisputeResolved",
          inputs: [
            {
              name: "proposalNode",
              type: "bytes32",
              indexed: true,
              internalType: "bytes32",
            },
            {
              name: "refunded",
              type: "bool",
              indexed: false,
              internalType: "bool",
            },
          ],
          anonymous: false,
        },
        {
          type: "event",
          name: "Disputed",
          inputs: [
            {
              name: "proposalNode",
              type: "bytes32",
              indexed: true,
              internalType: "bytes32",
            },
            {
              name: "raiser",
              type: "address",
              indexed: true,
              internalType: "address",
            },
          ],
          anonymous: false,
        },
        {
          type: "event",
          name: "Expired",
          inputs: [
            {
              name: "proposalNode",
              type: "bytes32",
              indexed: true,
              internalType: "bytes32",
            },
          ],
          anonymous: false,
        },
        {
          type: "event",
          name: "MilestoneReleased",
          inputs: [
            {
              name: "proposalNode",
              type: "bytes32",
              indexed: true,
              internalType: "bytes32",
            },
            {
              name: "milestone",
              type: "uint8",
              indexed: true,
              internalType: "uint8",
            },
            {
              name: "amount",
              type: "uint256",
              indexed: false,
              internalType: "uint256",
            },
          ],
          anonymous: false,
        },
        {
          type: "event",
          name: "ProposalCreated",
          inputs: [
            {
              name: "proposalNode",
              type: "bytes32",
              indexed: true,
              internalType: "bytes32",
            },
            {
              name: "neighborhoodId",
              type: "bytes32",
              indexed: true,
              internalType: "bytes32",
            },
            {
              name: "executor",
              type: "address",
              indexed: false,
              internalType: "address",
            },
          ],
          anonymous: false,
        },
        {
          type: "event",
          name: "Refunded",
          inputs: [
            {
              name: "proposalNode",
              type: "bytes32",
              indexed: true,
              internalType: "bytes32",
            },
            {
              name: "member",
              type: "address",
              indexed: true,
              internalType: "address",
            },
            {
              name: "amount",
              type: "uint256",
              indexed: false,
              internalType: "uint256",
            },
          ],
          anonymous: false,
        },
        {
          type: "event",
          name: "ThresholdMet",
          inputs: [
            {
              name: "proposalNode",
              type: "bytes32",
              indexed: true,
              internalType: "bytes32",
            },
            {
              name: "totalCommitted",
              type: "uint256",
              indexed: false,
              internalType: "uint256",
            },
            {
              name: "memberCount",
              type: "uint256",
              indexed: false,
              internalType: "uint256",
            },
          ],
          anonymous: false,
        },
        {
          type: "event",
          name: "Withdrawn",
          inputs: [
            {
              name: "proposalNode",
              type: "bytes32",
              indexed: true,
              internalType: "bytes32",
            },
            {
              name: "member",
              type: "address",
              indexed: true,
              internalType: "address",
            },
            {
              name: "amount",
              type: "uint256",
              indexed: false,
              internalType: "uint256",
            },
          ],
          anonymous: false,
        },
        {
          type: "error",
          name: "AlreadyAttested",
          inputs: [],
        },
        {
          type: "error",
          name: "AmountZero",
          inputs: [],
        },
        {
          type: "error",
          name: "MilestoneAlreadyReleased",
          inputs: [],
        },
        {
          type: "error",
          name: "MilestoneNotReady",
          inputs: [],
        },
        {
          type: "error",
          name: "NotActive",
          inputs: [],
        },
        {
          type: "error",
          name: "NotAdmin",
          inputs: [],
        },
        {
          type: "error",
          name: "NotExpired",
          inputs: [],
        },
        {
          type: "error",
          name: "NotMember",
          inputs: [],
        },
        {
          type: "error",
          name: "PastDeadline",
          inputs: [],
        },
        {
          type: "error",
          name: "ReentrancyGuardReentrantCall",
          inputs: [],
        },
        {
          type: "error",
          name: "SafeERC20FailedOperation",
          inputs: [
            {
              name: "token",
              type: "address",
              internalType: "address",
            },
          ],
        },
        {
          type: "error",
          name: "StringsInsufficientHexLength",
          inputs: [
            {
              name: "value",
              type: "uint256",
              internalType: "uint256",
            },
            {
              name: "length",
              type: "uint256",
              internalType: "uint256",
            },
          ],
        },
        {
          type: "error",
          name: "WrongStatus",
          inputs: [],
        },
      ],
      inheritedFunctions: {},
      deployedOnBlock: 2,
    },
  },
  84532: {
    ObecRegistry: {
      address: "0xeda49db1213e783ef25de41f9b4e82711f8d7bbd",
      abi: [
        {
          type: "constructor",
          inputs: [
            {
              name: "protocolRootNamehash",
              type: "bytes32",
              internalType: "bytes32",
            },
          ],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "PROTOCOL_ROOT_NAMEHASH",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "bytes32",
              internalType: "bytes32",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "addressToNode",
          inputs: [
            {
              name: "",
              type: "address",
              internalType: "address",
            },
          ],
          outputs: [
            {
              name: "",
              type: "bytes32",
              internalType: "bytes32",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "commitmentPool",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "address",
              internalType: "address",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "createNeighborhood",
          inputs: [
            {
              name: "city",
              type: "string",
              internalType: "string",
            },
            {
              name: "name",
              type: "string",
              internalType: "string",
            },
          ],
          outputs: [
            {
              name: "neighborhoodId",
              type: "bytes32",
              internalType: "bytes32",
            },
          ],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "deactivateResource",
          inputs: [
            {
              name: "node",
              type: "bytes32",
              internalType: "bytes32",
            },
          ],
          outputs: [],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "getContenthash",
          inputs: [
            {
              name: "node",
              type: "bytes32",
              internalType: "bytes32",
            },
          ],
          outputs: [
            {
              name: "",
              type: "bytes",
              internalType: "bytes",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "getNeighborhoodMembers",
          inputs: [
            {
              name: "neighborhoodId",
              type: "bytes32",
              internalType: "bytes32",
            },
          ],
          outputs: [
            {
              name: "",
              type: "bytes32[]",
              internalType: "bytes32[]",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "getNeighborhoodResources",
          inputs: [
            {
              name: "neighborhoodId",
              type: "bytes32",
              internalType: "bytes32",
            },
          ],
          outputs: [
            {
              name: "",
              type: "bytes32[]",
              internalType: "bytes32[]",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "getNodeByAddress",
          inputs: [
            {
              name: "wallet",
              type: "address",
              internalType: "address",
            },
          ],
          outputs: [
            {
              name: "",
              type: "bytes32",
              internalType: "bytes32",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "getNodeLabels",
          inputs: [
            {
              name: "node",
              type: "bytes32",
              internalType: "bytes32",
            },
          ],
          outputs: [
            {
              name: "",
              type: "string[]",
              internalType: "string[]",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "getText",
          inputs: [
            {
              name: "node",
              type: "bytes32",
              internalType: "bytes32",
            },
            {
              name: "key",
              type: "string",
              internalType: "string",
            },
          ],
          outputs: [
            {
              name: "",
              type: "string",
              internalType: "string",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "isMember",
          inputs: [
            {
              name: "neighborhoodId",
              type: "bytes32",
              internalType: "bytes32",
            },
            {
              name: "wallet",
              type: "address",
              internalType: "address",
            },
          ],
          outputs: [
            {
              name: "",
              type: "bool",
              internalType: "bool",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "joinNeighborhood",
          inputs: [
            {
              name: "neighborhoodId",
              type: "bytes32",
              internalType: "bytes32",
            },
            {
              name: "label",
              type: "string",
              internalType: "string",
            },
          ],
          outputs: [
            {
              name: "memberNode",
              type: "bytes32",
              internalType: "bytes32",
            },
          ],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "members",
          inputs: [
            {
              name: "",
              type: "bytes32",
              internalType: "bytes32",
            },
          ],
          outputs: [
            {
              name: "wallet",
              type: "address",
              internalType: "address",
            },
            {
              name: "neighborhoodId",
              type: "bytes32",
              internalType: "bytes32",
            },
            {
              name: "label",
              type: "string",
              internalType: "string",
            },
            {
              name: "joinedAt",
              type: "uint64",
              internalType: "uint64",
            },
            {
              name: "active",
              type: "bool",
              internalType: "bool",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "neighborhoodAdmin",
          inputs: [
            {
              name: "neighborhoodId",
              type: "bytes32",
              internalType: "bytes32",
            },
          ],
          outputs: [
            {
              name: "",
              type: "address",
              internalType: "address",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "neighborhoodMembers",
          inputs: [
            {
              name: "",
              type: "bytes32",
              internalType: "bytes32",
            },
            {
              name: "",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          outputs: [
            {
              name: "",
              type: "bytes32",
              internalType: "bytes32",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "neighborhoodResources",
          inputs: [
            {
              name: "",
              type: "bytes32",
              internalType: "bytes32",
            },
            {
              name: "",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          outputs: [
            {
              name: "",
              type: "bytes32",
              internalType: "bytes32",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "neighborhoods",
          inputs: [
            {
              name: "",
              type: "bytes32",
              internalType: "bytes32",
            },
          ],
          outputs: [
            {
              name: "city",
              type: "string",
              internalType: "string",
            },
            {
              name: "name",
              type: "string",
              internalType: "string",
            },
            {
              name: "admin",
              type: "address",
              internalType: "address",
            },
            {
              name: "active",
              type: "bool",
              internalType: "bool",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "owner",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "address",
              internalType: "address",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "registerResource",
          inputs: [
            {
              name: "neighborhoodId",
              type: "bytes32",
              internalType: "bytes32",
            },
            {
              name: "label",
              type: "string",
              internalType: "string",
            },
            {
              name: "resourceType",
              type: "string",
              internalType: "string",
            },
            {
              name: "fundedBy",
              type: "address",
              internalType: "address",
            },
          ],
          outputs: [
            {
              name: "resourceNode",
              type: "bytes32",
              internalType: "bytes32",
            },
          ],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "resources",
          inputs: [
            {
              name: "",
              type: "bytes32",
              internalType: "bytes32",
            },
          ],
          outputs: [
            {
              name: "neighborhoodId",
              type: "bytes32",
              internalType: "bytes32",
            },
            {
              name: "label",
              type: "string",
              internalType: "string",
            },
            {
              name: "resourceType",
              type: "string",
              internalType: "string",
            },
            {
              name: "fundedBy",
              type: "address",
              internalType: "address",
            },
            {
              name: "active",
              type: "bool",
              internalType: "bool",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "setCommitmentPool",
          inputs: [
            {
              name: "pool",
              type: "address",
              internalType: "address",
            },
          ],
          outputs: [],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "setContenthash",
          inputs: [
            {
              name: "node",
              type: "bytes32",
              internalType: "bytes32",
            },
            {
              name: "hash",
              type: "bytes",
              internalType: "bytes",
            },
          ],
          outputs: [],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "setText",
          inputs: [
            {
              name: "node",
              type: "bytes32",
              internalType: "bytes32",
            },
            {
              name: "key",
              type: "string",
              internalType: "string",
            },
            {
              name: "value",
              type: "string",
              internalType: "string",
            },
          ],
          outputs: [],
          stateMutability: "nonpayable",
        },
        {
          type: "event",
          name: "CommitmentPoolSet",
          inputs: [
            {
              name: "pool",
              type: "address",
              indexed: false,
              internalType: "address",
            },
          ],
          anonymous: false,
        },
        {
          type: "event",
          name: "ContenthashSet",
          inputs: [
            {
              name: "node",
              type: "bytes32",
              indexed: true,
              internalType: "bytes32",
            },
            {
              name: "hash",
              type: "bytes",
              indexed: false,
              internalType: "bytes",
            },
          ],
          anonymous: false,
        },
        {
          type: "event",
          name: "MemberJoined",
          inputs: [
            {
              name: "neighborhoodId",
              type: "bytes32",
              indexed: true,
              internalType: "bytes32",
            },
            {
              name: "memberNode",
              type: "bytes32",
              indexed: true,
              internalType: "bytes32",
            },
            {
              name: "wallet",
              type: "address",
              indexed: false,
              internalType: "address",
            },
            {
              name: "label",
              type: "string",
              indexed: false,
              internalType: "string",
            },
          ],
          anonymous: false,
        },
        {
          type: "event",
          name: "NeighborhoodCreated",
          inputs: [
            {
              name: "neighborhoodId",
              type: "bytes32",
              indexed: true,
              internalType: "bytes32",
            },
            {
              name: "city",
              type: "string",
              indexed: false,
              internalType: "string",
            },
            {
              name: "name",
              type: "string",
              indexed: false,
              internalType: "string",
            },
            {
              name: "admin",
              type: "address",
              indexed: false,
              internalType: "address",
            },
          ],
          anonymous: false,
        },
        {
          type: "event",
          name: "ResourceDeactivated",
          inputs: [
            {
              name: "neighborhoodId",
              type: "bytes32",
              indexed: true,
              internalType: "bytes32",
            },
            {
              name: "resourceNode",
              type: "bytes32",
              indexed: true,
              internalType: "bytes32",
            },
          ],
          anonymous: false,
        },
        {
          type: "event",
          name: "ResourceRegistered",
          inputs: [
            {
              name: "neighborhoodId",
              type: "bytes32",
              indexed: true,
              internalType: "bytes32",
            },
            {
              name: "resourceNode",
              type: "bytes32",
              indexed: true,
              internalType: "bytes32",
            },
            {
              name: "label",
              type: "string",
              indexed: false,
              internalType: "string",
            },
            {
              name: "resourceType",
              type: "string",
              indexed: false,
              internalType: "string",
            },
          ],
          anonymous: false,
        },
        {
          type: "event",
          name: "TextSet",
          inputs: [
            {
              name: "node",
              type: "bytes32",
              indexed: true,
              internalType: "bytes32",
            },
            {
              name: "key",
              type: "string",
              indexed: false,
              internalType: "string",
            },
            {
              name: "value",
              type: "string",
              indexed: false,
              internalType: "string",
            },
          ],
          anonymous: false,
        },
        {
          type: "error",
          name: "AlreadyExists",
          inputs: [],
        },
        {
          type: "error",
          name: "NeighborhoodNotFound",
          inputs: [],
        },
        {
          type: "error",
          name: "NotOwner",
          inputs: [],
        },
        {
          type: "error",
          name: "NotPool",
          inputs: [],
        },
        {
          type: "error",
          name: "PoolAlreadySet",
          inputs: [],
        },
        {
          type: "error",
          name: "ResourceNotActive",
          inputs: [],
        },
        {
          type: "error",
          name: "Unauthorized",
          inputs: [],
        },
      ],
      inheritedFunctions: {},
      deployedOnBlock: 41301709,
    },
    MockUSDC: {
      address: "0x60e311214a3cb883032a270ec7dc2f42905cbd1f",
      abi: [
        {
          type: "constructor",
          inputs: [],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "allowance",
          inputs: [
            {
              name: "owner",
              type: "address",
              internalType: "address",
            },
            {
              name: "spender",
              type: "address",
              internalType: "address",
            },
          ],
          outputs: [
            {
              name: "",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "approve",
          inputs: [
            {
              name: "spender",
              type: "address",
              internalType: "address",
            },
            {
              name: "value",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          outputs: [
            {
              name: "",
              type: "bool",
              internalType: "bool",
            },
          ],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "balanceOf",
          inputs: [
            {
              name: "account",
              type: "address",
              internalType: "address",
            },
          ],
          outputs: [
            {
              name: "",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "decimals",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "uint8",
              internalType: "uint8",
            },
          ],
          stateMutability: "pure",
        },
        {
          type: "function",
          name: "mint",
          inputs: [
            {
              name: "to",
              type: "address",
              internalType: "address",
            },
            {
              name: "amount",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          outputs: [],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "name",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "string",
              internalType: "string",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "symbol",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "string",
              internalType: "string",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "totalSupply",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "transfer",
          inputs: [
            {
              name: "to",
              type: "address",
              internalType: "address",
            },
            {
              name: "value",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          outputs: [
            {
              name: "",
              type: "bool",
              internalType: "bool",
            },
          ],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "transferFrom",
          inputs: [
            {
              name: "from",
              type: "address",
              internalType: "address",
            },
            {
              name: "to",
              type: "address",
              internalType: "address",
            },
            {
              name: "value",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          outputs: [
            {
              name: "",
              type: "bool",
              internalType: "bool",
            },
          ],
          stateMutability: "nonpayable",
        },
        {
          type: "event",
          name: "Approval",
          inputs: [
            {
              name: "owner",
              type: "address",
              indexed: true,
              internalType: "address",
            },
            {
              name: "spender",
              type: "address",
              indexed: true,
              internalType: "address",
            },
            {
              name: "value",
              type: "uint256",
              indexed: false,
              internalType: "uint256",
            },
          ],
          anonymous: false,
        },
        {
          type: "event",
          name: "Transfer",
          inputs: [
            {
              name: "from",
              type: "address",
              indexed: true,
              internalType: "address",
            },
            {
              name: "to",
              type: "address",
              indexed: true,
              internalType: "address",
            },
            {
              name: "value",
              type: "uint256",
              indexed: false,
              internalType: "uint256",
            },
          ],
          anonymous: false,
        },
        {
          type: "error",
          name: "ERC20InsufficientAllowance",
          inputs: [
            {
              name: "spender",
              type: "address",
              internalType: "address",
            },
            {
              name: "allowance",
              type: "uint256",
              internalType: "uint256",
            },
            {
              name: "needed",
              type: "uint256",
              internalType: "uint256",
            },
          ],
        },
        {
          type: "error",
          name: "ERC20InsufficientBalance",
          inputs: [
            {
              name: "sender",
              type: "address",
              internalType: "address",
            },
            {
              name: "balance",
              type: "uint256",
              internalType: "uint256",
            },
            {
              name: "needed",
              type: "uint256",
              internalType: "uint256",
            },
          ],
        },
        {
          type: "error",
          name: "ERC20InvalidApprover",
          inputs: [
            {
              name: "approver",
              type: "address",
              internalType: "address",
            },
          ],
        },
        {
          type: "error",
          name: "ERC20InvalidReceiver",
          inputs: [
            {
              name: "receiver",
              type: "address",
              internalType: "address",
            },
          ],
        },
        {
          type: "error",
          name: "ERC20InvalidSender",
          inputs: [
            {
              name: "sender",
              type: "address",
              internalType: "address",
            },
          ],
        },
        {
          type: "error",
          name: "ERC20InvalidSpender",
          inputs: [
            {
              name: "spender",
              type: "address",
              internalType: "address",
            },
          ],
        },
      ],
      inheritedFunctions: {},
      deployedOnBlock: 41301709,
    },
    CommitmentPool: {
      address: "0x054dbdded5eb83e602909aafcb1d41d83d83d09b",
      abi: [
        {
          type: "constructor",
          inputs: [
            {
              name: "_registry",
              type: "address",
              internalType: "address",
            },
            {
              name: "_usdc",
              type: "address",
              internalType: "address",
            },
          ],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "MILESTONE_0_BPS",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "uint16",
              internalType: "uint16",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "MILESTONE_1_BPS",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "uint16",
              internalType: "uint16",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "MILESTONE_2_BPS",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "uint16",
              internalType: "uint16",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "attest",
          inputs: [
            {
              name: "proposalNode",
              type: "bytes32",
              internalType: "bytes32",
            },
          ],
          outputs: [],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "checkExpiry",
          inputs: [
            {
              name: "proposalNode",
              type: "bytes32",
              internalType: "bytes32",
            },
          ],
          outputs: [],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "claimRefund",
          inputs: [
            {
              name: "proposalNode",
              type: "bytes32",
              internalType: "bytes32",
            },
          ],
          outputs: [],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "claimWarrantyMilestone",
          inputs: [
            {
              name: "proposalNode",
              type: "bytes32",
              internalType: "bytes32",
            },
          ],
          outputs: [],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "commit",
          inputs: [
            {
              name: "proposalNode",
              type: "bytes32",
              internalType: "bytes32",
            },
            {
              name: "amount",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          outputs: [],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "commitments",
          inputs: [
            {
              name: "",
              type: "bytes32",
              internalType: "bytes32",
            },
            {
              name: "",
              type: "address",
              internalType: "address",
            },
          ],
          outputs: [
            {
              name: "",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "createProposal",
          inputs: [
            {
              name: "p",
              type: "tuple",
              internalType: "struct CommitmentPool.CreateParams",
              components: [
                {
                  name: "neighborhoodId",
                  type: "bytes32",
                  internalType: "bytes32",
                },
                {
                  name: "label",
                  type: "string",
                  internalType: "string",
                },
                {
                  name: "executor",
                  type: "address",
                  internalType: "address",
                },
                {
                  name: "targetAmount",
                  type: "uint256",
                  internalType: "uint256",
                },
                {
                  name: "minMembers",
                  type: "uint256",
                  internalType: "uint256",
                },
                {
                  name: "deadline",
                  type: "uint64",
                  internalType: "uint64",
                },
                {
                  name: "warrantyDuration",
                  type: "uint64",
                  internalType: "uint64",
                },
                {
                  name: "attestationThreshold",
                  type: "uint256",
                  internalType: "uint256",
                },
                {
                  name: "resourceType",
                  type: "string",
                  internalType: "string",
                },
                {
                  name: "description",
                  type: "string",
                  internalType: "string",
                },
              ],
            },
          ],
          outputs: [
            {
              name: "proposalNode",
              type: "bytes32",
              internalType: "bytes32",
            },
          ],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "getAttesters",
          inputs: [
            {
              name: "node",
              type: "bytes32",
              internalType: "bytes32",
            },
          ],
          outputs: [
            {
              name: "",
              type: "address[]",
              internalType: "address[]",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "getProposal",
          inputs: [
            {
              name: "node",
              type: "bytes32",
              internalType: "bytes32",
            },
          ],
          outputs: [
            {
              name: "",
              type: "tuple",
              internalType: "struct CommitmentPool.Proposal",
              components: [
                {
                  name: "neighborhoodId",
                  type: "bytes32",
                  internalType: "bytes32",
                },
                {
                  name: "label",
                  type: "string",
                  internalType: "string",
                },
                {
                  name: "executor",
                  type: "address",
                  internalType: "address",
                },
                {
                  name: "targetAmount",
                  type: "uint256",
                  internalType: "uint256",
                },
                {
                  name: "minMembers",
                  type: "uint256",
                  internalType: "uint256",
                },
                {
                  name: "deadline",
                  type: "uint64",
                  internalType: "uint64",
                },
                {
                  name: "warrantyDuration",
                  type: "uint64",
                  internalType: "uint64",
                },
                {
                  name: "attestedAt",
                  type: "uint64",
                  internalType: "uint64",
                },
                {
                  name: "attestationThreshold",
                  type: "uint256",
                  internalType: "uint256",
                },
                {
                  name: "totalCommitted",
                  type: "uint256",
                  internalType: "uint256",
                },
                {
                  name: "memberCount",
                  type: "uint256",
                  internalType: "uint256",
                },
                {
                  name: "attestationCount",
                  type: "uint256",
                  internalType: "uint256",
                },
                {
                  name: "status",
                  type: "uint8",
                  internalType: "enum CommitmentPool.Status",
                },
                {
                  name: "milestoneReleased",
                  type: "bool[3]",
                  internalType: "bool[3]",
                },
              ],
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "hasAttested",
          inputs: [
            {
              name: "",
              type: "bytes32",
              internalType: "bytes32",
            },
            {
              name: "",
              type: "address",
              internalType: "address",
            },
          ],
          outputs: [
            {
              name: "",
              type: "bool",
              internalType: "bool",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "raiseDispute",
          inputs: [
            {
              name: "proposalNode",
              type: "bytes32",
              internalType: "bytes32",
            },
          ],
          outputs: [],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "registry",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "address",
              internalType: "contract IRegistry",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "resolveDispute",
          inputs: [
            {
              name: "proposalNode",
              type: "bytes32",
              internalType: "bytes32",
            },
            {
              name: "refund",
              type: "bool",
              internalType: "bool",
            },
          ],
          outputs: [],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "status",
          inputs: [
            {
              name: "node",
              type: "bytes32",
              internalType: "bytes32",
            },
          ],
          outputs: [
            {
              name: "",
              type: "uint8",
              internalType: "enum CommitmentPool.Status",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "usdc",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "address",
              internalType: "contract IERC20",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "withdraw",
          inputs: [
            {
              name: "proposalNode",
              type: "bytes32",
              internalType: "bytes32",
            },
          ],
          outputs: [],
          stateMutability: "nonpayable",
        },
        {
          type: "event",
          name: "Attested",
          inputs: [
            {
              name: "proposalNode",
              type: "bytes32",
              indexed: true,
              internalType: "bytes32",
            },
            {
              name: "member",
              type: "address",
              indexed: true,
              internalType: "address",
            },
            {
              name: "attestationCount",
              type: "uint256",
              indexed: false,
              internalType: "uint256",
            },
          ],
          anonymous: false,
        },
        {
          type: "event",
          name: "Committed",
          inputs: [
            {
              name: "proposalNode",
              type: "bytes32",
              indexed: true,
              internalType: "bytes32",
            },
            {
              name: "member",
              type: "address",
              indexed: true,
              internalType: "address",
            },
            {
              name: "amount",
              type: "uint256",
              indexed: false,
              internalType: "uint256",
            },
            {
              name: "totalCommitted",
              type: "uint256",
              indexed: false,
              internalType: "uint256",
            },
          ],
          anonymous: false,
        },
        {
          type: "event",
          name: "DisputeResolved",
          inputs: [
            {
              name: "proposalNode",
              type: "bytes32",
              indexed: true,
              internalType: "bytes32",
            },
            {
              name: "refunded",
              type: "bool",
              indexed: false,
              internalType: "bool",
            },
          ],
          anonymous: false,
        },
        {
          type: "event",
          name: "Disputed",
          inputs: [
            {
              name: "proposalNode",
              type: "bytes32",
              indexed: true,
              internalType: "bytes32",
            },
            {
              name: "raiser",
              type: "address",
              indexed: true,
              internalType: "address",
            },
          ],
          anonymous: false,
        },
        {
          type: "event",
          name: "Expired",
          inputs: [
            {
              name: "proposalNode",
              type: "bytes32",
              indexed: true,
              internalType: "bytes32",
            },
          ],
          anonymous: false,
        },
        {
          type: "event",
          name: "MilestoneReleased",
          inputs: [
            {
              name: "proposalNode",
              type: "bytes32",
              indexed: true,
              internalType: "bytes32",
            },
            {
              name: "milestone",
              type: "uint8",
              indexed: true,
              internalType: "uint8",
            },
            {
              name: "amount",
              type: "uint256",
              indexed: false,
              internalType: "uint256",
            },
          ],
          anonymous: false,
        },
        {
          type: "event",
          name: "ProposalCreated",
          inputs: [
            {
              name: "proposalNode",
              type: "bytes32",
              indexed: true,
              internalType: "bytes32",
            },
            {
              name: "neighborhoodId",
              type: "bytes32",
              indexed: true,
              internalType: "bytes32",
            },
            {
              name: "executor",
              type: "address",
              indexed: false,
              internalType: "address",
            },
          ],
          anonymous: false,
        },
        {
          type: "event",
          name: "Refunded",
          inputs: [
            {
              name: "proposalNode",
              type: "bytes32",
              indexed: true,
              internalType: "bytes32",
            },
            {
              name: "member",
              type: "address",
              indexed: true,
              internalType: "address",
            },
            {
              name: "amount",
              type: "uint256",
              indexed: false,
              internalType: "uint256",
            },
          ],
          anonymous: false,
        },
        {
          type: "event",
          name: "ThresholdMet",
          inputs: [
            {
              name: "proposalNode",
              type: "bytes32",
              indexed: true,
              internalType: "bytes32",
            },
            {
              name: "totalCommitted",
              type: "uint256",
              indexed: false,
              internalType: "uint256",
            },
            {
              name: "memberCount",
              type: "uint256",
              indexed: false,
              internalType: "uint256",
            },
          ],
          anonymous: false,
        },
        {
          type: "event",
          name: "Withdrawn",
          inputs: [
            {
              name: "proposalNode",
              type: "bytes32",
              indexed: true,
              internalType: "bytes32",
            },
            {
              name: "member",
              type: "address",
              indexed: true,
              internalType: "address",
            },
            {
              name: "amount",
              type: "uint256",
              indexed: false,
              internalType: "uint256",
            },
          ],
          anonymous: false,
        },
        {
          type: "error",
          name: "AlreadyAttested",
          inputs: [],
        },
        {
          type: "error",
          name: "AmountZero",
          inputs: [],
        },
        {
          type: "error",
          name: "MilestoneAlreadyReleased",
          inputs: [],
        },
        {
          type: "error",
          name: "MilestoneNotReady",
          inputs: [],
        },
        {
          type: "error",
          name: "NotActive",
          inputs: [],
        },
        {
          type: "error",
          name: "NotAdmin",
          inputs: [],
        },
        {
          type: "error",
          name: "NotExpired",
          inputs: [],
        },
        {
          type: "error",
          name: "NotMember",
          inputs: [],
        },
        {
          type: "error",
          name: "PastDeadline",
          inputs: [],
        },
        {
          type: "error",
          name: "ReentrancyGuardReentrantCall",
          inputs: [],
        },
        {
          type: "error",
          name: "SafeERC20FailedOperation",
          inputs: [
            {
              name: "token",
              type: "address",
              internalType: "address",
            },
          ],
        },
        {
          type: "error",
          name: "StringsInsufficientHexLength",
          inputs: [
            {
              name: "value",
              type: "uint256",
              internalType: "uint256",
            },
            {
              name: "length",
              type: "uint256",
              internalType: "uint256",
            },
          ],
        },
        {
          type: "error",
          name: "WrongStatus",
          inputs: [],
        },
      ],
      inheritedFunctions: {},
      deployedOnBlock: 41301709,
    },
  },
  11155111: {
    ObecResolver: {
      address: "0xeda49db1213e783ef25de41f9b4e82711f8d7bbd",
      abi: [
        {
          type: "constructor",
          inputs: [
            {
              name: "_urls",
              type: "string[]",
              internalType: "string[]",
            },
            {
              name: "_signer",
              type: "address",
              internalType: "address",
            },
          ],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "gatewayUrls",
          inputs: [
            {
              name: "",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          outputs: [
            {
              name: "",
              type: "string",
              internalType: "string",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "isSigner",
          inputs: [
            {
              name: "",
              type: "address",
              internalType: "address",
            },
          ],
          outputs: [
            {
              name: "",
              type: "bool",
              internalType: "bool",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "owner",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "address",
              internalType: "address",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "resolve",
          inputs: [
            {
              name: "name",
              type: "bytes",
              internalType: "bytes",
            },
            {
              name: "data",
              type: "bytes",
              internalType: "bytes",
            },
          ],
          outputs: [
            {
              name: "",
              type: "bytes",
              internalType: "bytes",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "resolveWithProof",
          inputs: [
            {
              name: "response",
              type: "bytes",
              internalType: "bytes",
            },
            {
              name: "extraData",
              type: "bytes",
              internalType: "bytes",
            },
          ],
          outputs: [
            {
              name: "",
              type: "bytes",
              internalType: "bytes",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "setGatewayUrls",
          inputs: [
            {
              name: "urls",
              type: "string[]",
              internalType: "string[]",
            },
          ],
          outputs: [],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "setSigner",
          inputs: [
            {
              name: "signer",
              type: "address",
              internalType: "address",
            },
            {
              name: "allowed",
              type: "bool",
              internalType: "bool",
            },
          ],
          outputs: [],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "supportsInterface",
          inputs: [
            {
              name: "interfaceId",
              type: "bytes4",
              internalType: "bytes4",
            },
          ],
          outputs: [
            {
              name: "",
              type: "bool",
              internalType: "bool",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "transferOwnership",
          inputs: [
            {
              name: "newOwner",
              type: "address",
              internalType: "address",
            },
          ],
          outputs: [],
          stateMutability: "nonpayable",
        },
        {
          type: "event",
          name: "GatewayUrlsSet",
          inputs: [
            {
              name: "urls",
              type: "string[]",
              indexed: false,
              internalType: "string[]",
            },
          ],
          anonymous: false,
        },
        {
          type: "event",
          name: "OwnerTransferred",
          inputs: [
            {
              name: "previousOwner",
              type: "address",
              indexed: false,
              internalType: "address",
            },
            {
              name: "newOwner",
              type: "address",
              indexed: false,
              internalType: "address",
            },
          ],
          anonymous: false,
        },
        {
          type: "event",
          name: "SignerSet",
          inputs: [
            {
              name: "signer",
              type: "address",
              indexed: false,
              internalType: "address",
            },
            {
              name: "allowed",
              type: "bool",
              indexed: false,
              internalType: "bool",
            },
          ],
          anonymous: false,
        },
        {
          type: "error",
          name: "ECDSAInvalidSignature",
          inputs: [],
        },
        {
          type: "error",
          name: "ECDSAInvalidSignatureLength",
          inputs: [
            {
              name: "length",
              type: "uint256",
              internalType: "uint256",
            },
          ],
        },
        {
          type: "error",
          name: "ECDSAInvalidSignatureS",
          inputs: [
            {
              name: "s",
              type: "bytes32",
              internalType: "bytes32",
            },
          ],
        },
        {
          type: "error",
          name: "NotOwner",
          inputs: [],
        },
        {
          type: "error",
          name: "OffchainLookup",
          inputs: [
            {
              name: "sender",
              type: "address",
              internalType: "address",
            },
            {
              name: "urls",
              type: "string[]",
              internalType: "string[]",
            },
            {
              name: "callData",
              type: "bytes",
              internalType: "bytes",
            },
            {
              name: "callbackFunction",
              type: "bytes4",
              internalType: "bytes4",
            },
            {
              name: "extraData",
              type: "bytes",
              internalType: "bytes",
            },
          ],
        },
        {
          type: "error",
          name: "SignatureExpired",
          inputs: [],
        },
        {
          type: "error",
          name: "UnauthorizedSigner",
          inputs: [],
        },
      ],
      inheritedFunctions: {},
      deployedOnBlock: 10823647,
    },
  },
} as const;

export default deployedContracts satisfies GenericContractsDeclaration;
